### ISSUE TITLE
Annotate animation frames with iteration number

### ISSUE THREAD

**Issue by WheezePuppet** [WheezePuppet/specnet#25]
Currently the animation is difficult to interpret, as it simply cycles through all the frames and starts over at the beginning. It would be better if the frames had some text annotation saying "Iteration 19 of 100..." or some such, so that this is available to the viewer as the animation progresses.

**Comment by will-nehrboss** [comment]
My current solution is pretty straightforward.
During the creating of the svg files of the animation, I append a tag with the iteration number to the image.

  run(`mogrify -format svg -gravity South  -pointsize 15 -annotate 0 "Iteration $(iter) of $(num_iter)"  
 $(tempdir())\output$(lpad(string(iter),3,'0')).png`)

instead of :

run(`mogrify -format svg $(tempdir())/output"*".png`)
 
I also put the svg creation in a second make_anim conditional in the main loop to sync it with iter. 
Initially, I tried to work with the graph creation before the png was made, but this was a more straightforward option. It works on my end, let me know if this is an acceptable solution.

**Comment by WheezePuppet** [comment]
D'oh! Why didn't I think of that. Excellent solution!

**Comment by WheezePuppet** [comment]
Closing this because I believe @will-nehrboss has finished this and checked it in. (If not, please reopen.)
