### ISSUE TITLE
Create "the current model, explained in words"

### ISSUE THREAD

**Issue by WheezePuppet** [WheezePuppet/specnet#8]
A question any of us might ask at any point in time: "As of this instant, what exactly does the current SPECnet (or SPECscape) simulation do?"

One way to answer this is to look at the Julia code, which is of course by definition the answer. But it occurs to me that: 

1. not everyone (perhaps not Rajesh or Milton) is good at understanding code, and
2. looking at code engulfs one in implementation-specific minutiae that doesn't speak to the more conceptual question anyway, and
3. there's the possibility of bugs: the code as written incorrectly implements what we intended to be "the way it works."

It seems valuable therefore to maintain a page (for each project) called something like "Current Model" which:

* describes in plain, but detailed, English exactly what the current version of the code does
* is kept rigorously in-sync with the actual code base so that the Rajesh's and Milton's of the world are always looking at the up-to-date model description.

(We could write these in [ODD](https://www.ethz.ch/content/dam/ethz/special-interest/usys/ites/ecosystem-management-dam/documents/EducationDOC/EM_DOC/Recommended%20readingDOC/Grimm_2010.pdf), though I'd prefer a less stringent, less verbose style.)

Curious as to whether @venkatachalapathy, @IngenuityArts, and @srikanthmudigonda agree this is a good idea, and if so, what's the appropriate place to put these "Current Models":
* github wiki page? (which we have said we abandoned)
* github "issue"? (which seems like the wrong thing for ongoing, maintained content)
* on PubPub?

**Comment by IngenuityArts** [comment]
I'm not sure about location but I think this is an important point - code development + current plain language descriptions of what is happening. While it is more work and slower, it has the benefit of putting conceptions into specific code form and of keeping the code subjected to conceptual and experimental needs and interests. 

That mutuality is important and allows extension both ways - into communities that are interested in testing ideas and hypotheses (policy, application side people) - as well as into the technical coding side where improved tools, techniques, and approaches are needed to achieve understanding. 

It embodies, I think, the very strength we are working to develop among ourselves, that our differences can be significant prompts toward actual innovation and insight.

**Comment by venkatachalapathy** [comment]
I would prefer a less formal but simple language way to describe the model changes. 

I think at this point, we should just go ahead with things without worrying too much about it. At some point, the model is going to have too many bells and whistles that incremental changes might make sense only to the coder but even then, clearly written commit messages and creating issues for every incremental model enhancements should suffice. 

For example, in order to go from Model $i$ to Model $i+1$

1.  Create an issue saying so
2.  Tag that issue as `enhancement` __X__
3.  Now suppose the during the course of `enhancement` __X__ , one finds the need to break it down to smaller chunks, go to step 1
4.  Close the sub-enhancements before we close the main enhancement
5.  After all the enhancements are closed, close `enhancement` __X__

So, we keep track of model evolution using issues.

**Comment by WheezePuppet** [comment]
Okay, but I still like the idea of a continually-up-to-date "current model" page that represents what the simulation currently does. Otherwise, if Rajesh/Milton/Srikanth/whoever wondered (for example), "does the current SPECnet model permit agents to form proto-institutions with non-network-neighbors, or does it not?" there's no easy way to quickly answer that without combing through (a) the code, or (b) the issues database, to construct the answer.

**Comment by venkatachalapathy** [comment]
I think we are in agreement here.
